### ISSUE TITLE
Visualization tracker 

### ISSUE THREAD

**Issue by deepaknevdepsl** [spattnaik/opensearch-planning#1]
### Open PR's for code review 
---

- [ ] @rinku-kumar-psl https://github.com/opensearch-project/observability/pull/784
- [ ] @rinku-kumar-psl https://github.com/opensearch-project/observability/pull/780
- [ ] @ruchika-narang  https://github.com/opensearch-project/observability/pull/778
- [ ] @deepaknevdepsl  https://github.com/opensearch-project/observability/pull/776
- [ ] @pratibhapandey16 https://github.com/opensearch-project/observability/pull/759
- [ ] @ruchika-narang https://github.com/opensearch-project/observability/pull/743
- [x] @mrunal-z https://github.com/opensearch-project/observability/pull/693

### List of issues/features
---

<details><summary>Legend</summary>
<p dir="auto">
</p><table role="table">
<tbody>
<tr>
<td><g-emoji class="g-emoji" alias="green_circle" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f7e2.png">🟢 In progress </g-emoji></td>

<td><g-emoji class="g-emoji" alias="yellow_circle" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f7e1.png">🟡 Delayed </g-emoji></td>
<td><g-emoji class="g-emoji" alias="red_circle" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f534.png">🔴 Blocked </g-emoji></td>
<td><g-emoji class="g-emoji" alias="red_circle" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f534.png">
<img src="https://cdn3.emoji.gg/emojis/1537_pink_circle.png" width="17px" height="17px" alt="pink_circle">
</g-emoji> On hold </td>
</tr>
</tbody>
</table>
<p dir="auto"></p>
</details>

- [ ] https://github.com/opensearch-project/observability/issues/791  🟢
- [ ] https://github.com/opensearch-project/observability/issues/792  🟢
- [ ] https://github.com/opensearch-project/observability/issues/793  🟢
- [ ] https://github.com/opensearch-project/observability/issues/794  🟢
- [ ] https://github.com/opensearch-project/observability/issues/795  🟢
- [ ] https://github.com/opensearch-project/observability/issues/796  🟢
- [ ] https://github.com/opensearch-project/observability/issues/797  🟢
- [ ] https://github.com/opensearch-project/observability/issues/798  🟢
- [ ] https://github.com/opensearch-project/observability/issues/774  🟢
- [ ] https://github.com/opensearch-project/observability/issues/774  🟢
- [ ] https://github.com/opensearch-project/observability/issues/773  🟢
- [ ] https://github.com/opensearch-project/observability/issues/772  🟢
- [x] https://github.com/opensearch-project/observability/issues/777
- [x] https://github.com/opensearch-project/observability/issues/682

**Comment by deepaknevdepsl** [comment]
### General list of issues 
---

- [ ] https://github.com/opensearch-project/observability/issues/774 
- [ ] https://github.com/opensearch-project/observability/issues/773
- [ ] https://github.com/opensearch-project/observability/issues/772
- [ ] https://github.com/opensearch-project/observability/issues/777
- [ ] https://github.com/opensearch-project/observability/issues/682



### Open PR's for code review 
---

- [ ] https://github.com/opensearch-project/observability/pull/784
- [ ] https://github.com/opensearch-project/observability/pull/780
- [ ] https://github.com/opensearch-project/observability/pull/778
- [ ] https://github.com/opensearch-project/observability/pull/776
- [ ] https://github.com/opensearch-project/observability/pull/759
- [ ] https://github.com/opensearch-project/observability/pull/743
- [ ] https://github.com/opensearch-project/observability/pull/693


### OpenSearch | Team distribution 
---
 `<table id='simple_table' >
<tr>
	<th>Sr. No</th>
	<th>Owner Name</th>
	<th>Tasks / Deliverables</th>
	<th>Status</th>
	<th>Comments / Blockers</th>
	<th>Available for next tasks</th>
</tr>

<tr>
	<td>1.</td>
	<td>Nidhi Singhai</td>
	<td>Cypress testing PR for trace analytics dashboard </td>
	<td>Done</td>
	<td>Team will prepare the test cases on operational and notebook</td>
	<td>Available</td>
</tr>
<tr>
	<td>2.</td>
	<td>Pratibha Pandey</td>
	<td>Cypress testing PR for trace analytics dashboard </td>
	<td>Done</td>
	<td>Team will prepare the test cases on operational and notebook</td>
	<td>Available</td>
</tr>
<tr>
	<td rowspan="3">3.</td>
	<td rowspan="3">Rinku Kumar</td>
	<td>Showing Toast message to user on save button click. (when user didn’t select any of the value options)</td>
	<td>Dev Complete</td>
	<td>Review Approval pending</td>
	<td>Available</td>
</tr>

<tr>
	<td>Line Chart</td>
	<td>Dev Complete</td>
	<td>Review Approval pending</td>
	<td>Available</td>
</tr>

<tr>
	<td>Bar Chart</td>
	<td>Dev Complete</td>
	<td>Review Approval pending</td>
	<td>Available</td>
</tr>

<tr>
	<td>4.</td>
	<td>Abhay Pandey</td>
	<td>Nginx</td>
	<td>On Hold</td>
	<td>As per discussion with Anirudha keep this on hold</td>
	<td>Available</td>
</tr>
<tr>
	<td>5.</td>
	<td>Zishan Khan</td>
	<td>Kafka</td>
	<td>On Hold</td>
	<td>As per discussion with Anirudha keep this on hold</td>
	<td>Available</td>
</tr>
<tr>
	<td>6.</td>
	<td>Kuldeep Bhise</td>
	<td>Apache</td>
	<td>On Hold</td>
	<td>As per discussion with Anirudha keep this on hold</td>
	<td>Available</td>
</tr>
<tr>
	<td rowspan="3">7.</td>
	<td rowspan="3">Mrunal Zambre</td>
	<td>Exploration of config options</td>
	<td>In Progress</td>
	<td>Awaiting confirmation from Anirudha</td>
	<td rowspan="3">Available</td>
</tr>

<tr>
	<td>Tree Map Chart</td>
	<td>Dev Complete</td>
	<td>Review Approval pending</td>
</tr>

<tr>
	<td>Node Graph</td>
	<td>On Hold</td>
	<td>As per discussion with Anirudha keep this on hold</td>
</tr>

<tr>
	<td>8.</td>
	<td>Ramneet Chopra</td>
	<td>Table view replacement</td>
	<td>On Hold</td>
	<td>As per discussion with Anirudha keep this on hold</td>
	<td>Available</td>
</tr>
<tr>
	<td rowspan="2">9.</td>
	<td rowspan="2">Deepak Nevde</td>
	<td>Exploration of alert list</td>
	<td>On Hold</td>
	<td>As per discussion with Anirudha keep this on hold</td>
	<td rowspan="2">Available</td>
</tr>

<tr>
	<td>Pie Chart</td>
	<td>Dev Complete</td>
	<td>Review Approval pending</td>
</tr>

<tr>
	<td rowspan="3">10.</td>
	<td rowspan="3">Ruchika Narang</td>
	<td>Histogram Chart</td>
	<td>Dev Complete</td>
	<td>Review Approval pending</td>
	<td rowspan="3">Available</td>
</tr>

<tr>
	<td>Logs View</td>
	<td>On Hold</td>
	<td>As per discussion with Anirudha keep this on hold</td>
</tr>

<tr>
	<td>Heat Map</td>
	<td>Dev Complete</td>
	<td>Review Approval pending</td>
</tr>

<tr>
	<td>11.</td>
	<td>Amruta Basatwar</td>
	<td>Bar Chart</td>
	<td>Dev Complete</td>
	<td>Review Approval pending</td>
	<td>Available</td>
</tr>
<tr>
	<td>12.</td>
	<td>Tejal Borase</td>
	<td>Project overview and rampup</td>
	<td>In Progress</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>13.</td>
	<td>Naman Chaturvedi</td>
	<td>Project overview and rampup</td>
	<td>In Progress</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>14</td>
	<td>Mounika Erri</td>
	<td>Project overview and rampup</td>
	<td>In Progress</td>
	<td></td>
	<td></td>
</tr>
</table>`

**Comment by deepaknevdepsl** [comment]
### Daily task status 09 | June | 2022
---

<details><summary>Legend</summary>
<p dir="auto">
</p><table role="table">
<tbody>
<tr>
<td><g-emoji class="g-emoji" alias="green_circle" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f7e2.png">🟢 In progress </g-emoji></td>

<td><g-emoji class="g-emoji" alias="yellow_circle" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f7e1.png">🟡 Delayed </g-emoji></td>
<td><g-emoji class="g-emoji" alias="red_circle" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f534.png">🔴 Blocked </g-emoji></td>
<td>
<img src="https://cdn3.emoji.gg/emojis/1537_pink_circle.png" width="17px" height="17px" alt="pink_circle"> On hold </td>
<td  >
<a style="pointer-events: none;  cursor: default;" href="#"><img src="https://user-images.githubusercontent.com/102342039/173070978-5f9c1df4-5f5a-4d06-ad8f-2d7d01145d3a.png" width="18px"  height="18px" /> </a>PR Raised
</tr>
</tbody>
</table>
<p dir="auto"></p>
</details>

<table>
<tr>
	<th>Owner Name</th>
	<th>Tasks / Deliverables</th>
	<th>Status</th>
	<th>What you have done yesterday?</th>
	<th>what are you going to do today?</th>
	<th>Any impediments?</th>
	<th>Comments</th>
</tr>

<tr>
	<td>Nidhi Singhai</td>
	<td>Cypress test case for HeatMap are done and internal PR is raised</td>
	<td>🟢</td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>Pratibha Pandey</td>
	<td>Created internal PR for trace analytics dashboard cypress test cases</td>
	<td>🟢</td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>Rinku Kumar</td>
	<td>

- [ ] https://github.com/opensearch-project/observability/issues/666
- [ ] https://github.com/opensearch-project/observability/pull/736

</td>
	<td><a style="pointer-events: none;  cursor: default;" href="#"><img src="https://user-images.githubusercontent.com/102342039/173070978-5f9c1df4-5f5a-4d06-ad8f-2d7d01145d3a.png" width="22px"  height="22px" /> </a><br /></td>
	<td></td>
	<td></td>
	<td></td>
	<td>got one approval and waiting for another.</td>
</tr>

<tr>
	<td>Abhay Pandey</td>
	<td>

- [ ] https://github.com/opensearch-project/observability/issues/646

</td>
	<td>🟢</td>
	<td></td>
	<td></td>
	<td></td>
	<td>Added the nginx on the VM including fluentd.</td>
</tr>
<tr>
	<td>Zishan Khan</td>
	<td>

- [ ] https://github.com/opensearch-project/observability/issues/646

</td>
	<td>🟢</td>
	<td></td>
	<td></td>
	<td></td>
	<td>Added JSON format for the data and added the data validation part.</td>
</tr>
<tr>
	<td>Mrunal Zambre</td>
	<td>

- [ ] https://github.com/opensearch-project/observability/issues/768

</td>
	<td>🟢</td>
	<td></td>
	<td></td>
	<td></td>
	<td>Working on verifing and uploading document with findings.</td>
</tr>

<tr>
	<td>Ramneet Chopra</td>
	<td>

- [ ] https://github.com/opensearch-project/observability/issues/772 </td>
	<td>🟡</td>
	<td></td>
	<td></td>
	<td></td>
	<td>table view visualization column alignment via config panel</td>
</tr>
<tr>
	<td>Deepak Nevde</td>
	<td>

- [ ] https://github.com/opensearch-project/observability/issues/777

</td>
	<td>🟡</td>
	<td></td>
	<td></td>
	<td></td>
	<td>As per discussion with Anirudha keep this on hold</td>
</tr>

<tr>
	<td>Ruchika Narang</td>
	<td>

- [ ] https://github.com/opensearch-project/observability/issues/643
- [ ] https://github.com/opensearch-project/observability/pull/743

</td>
	<td><a style="pointer-events: none;  cursor: default;" href="#"><img src="https://user-images.githubusercontent.com/102342039/173070978-5f9c1df4-5f5a-4d06-ad8f-2d7d01145d3a.png" width="22px"  height="22px" /> </a></td>
	<td></td>
	<td></td>
	<td></td>
	<td>Review Approval pending</td>
</tr>
<tr>
	<td>Amruta Basatwar</td>
	<td>Bar Chart</td>
	<td>
<a style="pointer-events: none;  cursor: default;" href="#"><img src="https://user-images.githubusercontent.com/102342039/173070978-5f9c1df4-5f5a-4d06-ad8f-2d7d01145d3a.png" width="22px"  height="22px" /></a>
</td>
	<td></td>
	<td></td>
	<td></td>
	<td>Review Approval pending</td>
</tr>
<tr>
	<td>Tejal Borase</td>
	<td>Project overview and rampup</td>
	<td>🟢</td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>Naman Chaturvedi</td>
	<td>Project overview and rampup</td>
	<td>🟢</td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>Mounika Erri</td>
	<td>
Project overview and rampup
</td>
	<td>🟢</td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
</tr>
</table>

**Comment by abasatwar** [comment]
### Daily task status 10 | June | 2022
---
##### We have few queries to newly added tickets and need your inputs on those.
---
|Topic/ Ticket id|Dev |Status|Comments/Queries|what are you going to do today?|Any impediments?|
|:----|:----|:----|:----|:----|:----|
|Cypress testing - Notebook|Nidhi|In Progress|Analysed and started testcases for this.|Analysed and started testcases for this.| |
|Cypress testing - Operational Panels|Pratibha|In Progress|Analysed and started testcases for this.|Analysed and started testcases for this.| |
|Opensearch Server logs|Abhay|In Progress|analysing opensearch server logs to find our what metrics can be derived.|analysing opensearch server logs to find our what metrics can be derived.| |
|Nginx|Abhay|In Hold| | | |
|Apache +Fluent-bit|Kuldeep|In-progress|Configured the Fluent-bit  and exploration in progress.|Configured the Fluent-bit and exploration in progress.| |
|Kafka|Zishan|In-progress|Integration in progress| | |
|Exploration of config options|Mrunal|On hold|Created new tickets based on explored config options - https://github.com/opensearch-project/observability/issues/788, https://github.com/opensearch-project/observability/issues/789, https://github.com/opensearch-project/observability/issues/790 | |Need further discussion on created issues for this.|
|Table view replacement|Ramneet|On hold| | | |
|Github status tracker creation|Deepak|Done|Created github status tracker| | |
|Enhancement of Pie chart UI|Mrunal|In-progress|Created new ticket - https://github.com/opensearch-project/observability/issues/793| | |
|Enhancement of Treemap chart UI|Mrunal|In-progress|Created new ticket - https://github.com/opensearch-project/observability/issues/796| | |
|Enhancement of Heatmap chart UI|Ruchika|In-progress|Created new ticket - https://github.com/opensearch-project/observability/issues/791| | |
|Enhancement of Histogram chart UI|Ruchika|In-progress|Created new ticket - https://github.com/opensearch-project/observability/issues/795| | |
|Enhancement of Bar chart UI|Amruta|In-progress|Created new ticket - https://github.com/opensearch-project/observability/issues/792 | | |
|Enhancement of Time Series UI|Rinku|In-progress|Created new ticket - https://github.com/opensearch-project/observability/issues/794| | |
|UI changes #797|Deepak|In-progress|Created new ticket - https://github.com/opensearch-project/observability/issues/797 | | |
|PPL and UI communication as per # 787|Ramneet|In-progress|Created new ticket - https://github.com/opensearch-project/observability/issues/798 | | |

**Comment by abasatwar** [comment]
### Daily task status 13| June | 2022
---
|Topic/ Ticket id|Dev |Status|Comments/Queries|What you have done yesterday ?|what are you going to do today?|Any impediments?|
|:----|:----|:----|:----|:----|:----|:----|
|Cypress testing - Operational Panels(#801)|Nidhi|In Progress| |Analysed and started testcases for this.|Continuing testcases for Operational Panel| |
|Cypress testing - Notebook (#799)|Pratibha|In Progress| |Analysed and started testcases for this.|Continuing automating test cases for Notebook application|NA|
|Opensearch Server logs (#800)|Abhay|In Progress| |#Analysing the opensearch logs types.
#How we can read the logs and the location of the logs by using cloudwatch.|analysing opensearch server logs to find our what metrics can be derived.| |
|Nginx|Abhay|In Hold| |NA|NA| |
|Fluent-bit(#728)|Kuldeep|In-progress| |Explored on fluent-bit to read logs from access.log|Configuring Fluent-bit to read json format and started exploring kafka related stuff.| |
|Kafka|Zishan|In-progress|Integration in progress| |Reading about JMXTrans and its implementation to get Kafka Metrices.| |
|Exploration of config options|Mrunal|On hold|Created new tickets based on explored config options - https://github.com/opensearch- #788, #789, #790| | |Need further discussion on created issues for this.|
|Table view replacement (#772)|Ramneet|On hold| | | |waiting for inputs.|
|Enhancement of Treemap chart UI(#796)|Mrunal|In-progress| |Analysis of treemap UI enhancements as per #787 and listed queries for the same on ticket.|Started with implementation for new features| |
|Enhancement of Heatmap chart UI(#&91)|Ruchika|In-progress| |Analysis of heatmap UI enhancements as per #787 and listed queries for the same. Updated the open external PR after resolution of conflicts.|Started with implementation for new features| |
|Enhancement of Bar chart UI|Amruta|In-progress|Created new ticket - https://github.com/opensearch-project/observability/issues/792 |Analysis of features according to #787|Started with implementation for new features| |
|Enhancement of Time Series UI (794)|Rinku|In-progress|Queries added on github ticket #794.|Did analysis for time-series UI enhancement as per issue #787, and listed queries related to new Dimension UI integration|Will continue on analysis part of time-series and also work on new UI on config as per #787| |
|UI changes #797|Deepak|In-progress|Created new ticket - https://github.com/opensearch-project/observability/issues/797 |analysisng the requirements for UI for Data configuraitons|Static UI for Data configuraitons is in progress| |
|PPL and UI communication as per # 787|Ramneet|In-progress|Created new ticket - https://github.com/opensearch-project/observability/issues/798 |worked on suport of multiple dimensions on x axis for line chart. |explore ppl query integration in auto complete componentexplore dimensions creation for visulization| |
|Implementation on new Logs View and its Config-#697|Rinku|On hold| |Logs view Accordian panel UI created.|NA| |
|Implementation on Bar chart Config-#697|Rinku|In-progress|https://github.com/opensearch-project/observability/issues/802|NA|Working on resolving conflicts and code review comments| |

**Comment by abasatwar** [comment]
### Daily task status 14| June | 2022
---
|Topic/ Ticket id|Dev |Status|Comments/Queries|What you have done yesterday ?|what are you going to do today?|Any impediments?|
|:----|:----|:----|:----|:----|:----|:----|
|Cypress testing - Operational Panels(#801)|Nidhi|Completed| |Continuing testcases for Operational Panel|Raised Internal PR for Operational Test Case, Worked on Review Comment| |
|Cypress testing - Notebook (#799)|Pratibha|Completed| |Continuing automating test cases for Notebook application|Raised Internal PR for Operational Test Case and got approval for this|NA|
|Opensearch Server logs (#800)|Abhay|In Progress| |analysing opensearch server logs to find our what metrics can be derived.|Exploring the  Performance Analyzer for opensearch andExplored the perftop to get the opensearch metrices| |
|Nginx|Abhay|In Hold| |NA|NA| |
|Fluent-bit(#728)|Kuldeep|In-progress| |Configured Fluent-bit to read json format and started exploring kafka related stuff.|Started configuring JDK, Zookeeper and kafka. also looking into datadoghq for monitoring kafka matrics |NA|
|Kafka|Zishan|In-progress|Integration in progress| |Reading about JMXTrans and its implementation to get Kafka Metrices.| |
|Exploration of config options|Mrunal|On hold|Created new tickets based on explored config options - https://github.com/opensearch- #788, #789, #790| | |Need further discussion on created issues for this.|
|Table view replacement (#772)|Ramneet|On hold| | | |waiting for inputs.|
|Enhancement of Treemap chart UI(#796)|Mrunal|In-progress| |Analysis of treemap UI enhancements as per #787 and listed queries for the same on ticket.|Started with implementation for new features| |
|Enhancement of Heatmap chart UI(#791)|Ruchika|In-progress| |Analysis of heatmap UI enhancements as per #787 and listed queries for the same.|Started implementation for legend and dropped in a comment for findings of bottom right placement.| |
|Enhancement of Bar chart UI|Amruta|In-progress|Created new ticket - https://github.com/opensearch-project/observability/issues/792 |Analysis of features according to #787|Label size implementation is in progress| |
|Enhancement of Time Series UI (794)|Rinku|In-progress|As we facing dificulty to get multiple timestamp field response from ppl query. Please suggest a way to do the same for multi dimension.|Did analysis for time-series UI enhancement as per issue #787, and listed queries related to new Dimension UI integration|Explored multi axes support in plotly and how to return multiple timeStamp data in ppl response | |
|UI changes #797|Deepak|In-progress|Created new ticket - https://github.com/opensearch-project/observability/issues/797 |Static UI for Data configuraitons is in progress|Continue working onStatic UI for Data configuraitons is in progress| |
|PPL and UI communication as per # 787|Ramneet|In-progress|Created new ticket - https://github.com/opensearch-project/observability/issues/798 |explored ppl query integration in auto complete componentexplored dimensions creation for visulization|worked on ppl queries for dimensions and metrics | |
|Implementation on Bar chart Config-#697|Rinku|In-progress|We can update the Line chart PR if Bar chart will be merged as its contains few common component.|Resolved conflicts and code review comments.  PR updated|NA|Bar chart PR can be mearged after review: https://github.com/opensearch-project/observability/pull/780|
